### ISSUE TITLE
Steamdeck: No output device found, despite following guide.

### ISSUE THREAD

**Issue by MilanKladivko** [theNizo/linux_rocksmith#49] opened 2024-07-05 12:22 UTC
* Which distro do you use? **Steamdeck, Arch**
* Which Proton or wine version do you use? **Proton 8**
* Do you use pipewire? **Yes**
* Audio-Device used? **Lexicon Alpha, it's on RS_ASIO's supported devices list**

----

And here's a detailed log that I wrote as I was doing things for the 2nd+3rd time in case I missed something, over 2 separate days. 

I feel like I'm really close, so hopefully you see some small mistake that I migh've made. 

The whole process is "successful" and I ran everything as it's written in the Steamdeck guide, afaik.

```
# Running Rocksmith on a Steam Deck!!!!

https://github.com/theNizo/linux_rocksmith/blob/main/guides/setup/deck-pipewire.md#install-necessary-stuff
https://github.com/theNizo/linux_rocksmith/blob/main/guides/start-script/proton-8.md
https://github.com/theNizo/linux_rocksmith/blob/main/guides/setup-rs-asio.md

=============================================================================

Instal "qpwgraph" on Discover, "graph manager dedicated to PipeWire"

=============================================================================

Prep the OS packages (Deck = Arch = Pacman) and OS-user-groups

-----------------------------------------------------------------------------
# disable readonly mode
sudo steamos-readonly disable

sudo pacman-key --init
sudo pacman-key --populate archlinux

sudo pacman -S realtime-privileges wine-staging
# These packages are already on SteamOS so I did not install them:
# pipewire-alsa pipewire-pulse pipewire-jack lib32-pipewire-jack pavucontrol
# the groups should already exist, but just in case
sudo groupadd audio
sudo groupadd realtime
sudo usermod -aG audio $USER`
sudo usermod -aG realtime $USER`
=============================================================================

Log out and back in. Or reboot, if that doesn't work.
Those groupadds and usermods need it -- though they should exist anyway...?
Do it just in case.

=============================================================================

Define variables for $PROTON and $STEAMLIBRARY used throughout
You can put them in the .bashrc for having many terminals open easier

-----------------------------------------------------------------------------
##### VARIABLES FOR SETTING UP ROCKSMITH2014 (see ~/Applications/rocksmith/)
STEAMLIBRARY=/home/deck/.steam/steam/
# GE Proton 8
PROTON=/home/deck/.steam/steam/compatibilitytools.d/GE-Proton8-32/files/
# Proton 8 (non-GE, hopefully more tested/stable??)
PROTON=/home/deck/.steam/steam/steamapps/common/Proton\ 8.0/dist/
# Rocksmith wine prefix specifically
WINEPREFIX=/home/deck/.steam/steam/steamapps/compatdata/221680/pfx
=============================================================================

Build and "install" `wineasio` on the system itself (sudo cp into /usr/lib*)

-----------------------------------------------------------------------------
# build
rm -rf build32
rm -rf build64
make 32
make 64
# Install on normal wine
sudo cp build32/wineasio32.dll /usr/lib32/wine/i386-windows/wineasio32.dll
sudo cp build32/wineasio32.dll.so /usr/lib32/wine/i386-unix/wineasio32.dll.so
sudo cp build64/wineasio64.dll /usr/lib/wine/x86_64-windows/wineasio64.dll
sudo cp build64/wineasio64.dll.so /usr/lib/wine/x86_64-unix/wineasio64.dll.so
=============================================================================

Copy those DLLs into the Proton version used by Rocksmith

-----------------------------------------------------------------------------
cp /usr/lib32/wine/i386-unix/wineasio32.dll.so "$PROTON/lib/wine/i386-unix/wineasio.dll.so"
cp /usr/lib/wine/x86_64-unix/wineasio64.dll.so "$PROTON/lib64/wine/x86_64-unix/wineasio.dll.so"
cp /usr/lib32/wine/i386-windows/wineasio32.dll "$PROTON/lib/wine/i386-windows/wineasio.dll"
cp /usr/lib/wine/x86_64-windows/wineasio64.dll "$PROTON/lib64/wine/x86_64-windows/wineasio.dll"
=============================================================================

To register wineasio (so that it can be used in the prefix),
run the `wineasio-register` script that comes in the wineasio zip
while setting the WINEPREFIX to Rocksmith's.

I get a wine-UI window with "is being updated..."; if that's useful.

-----------------------------------------------------------------------------
env WINEPREFIX=$STEAMLIBRARY/steamapps/compatdata/221680/pfx ./wineasio-register
=============================================================================

ISSUE STARTS (maybe!)

The `./wineasio-register` command prints some errors -- but not on repeated
runs and only in a first one. Not sure when that resets, but I got back to it
and it did this again.

It might output even more errors about creating DLLs, I don't think
these are all there were.

But, it claims "successfully" so maybe it's nothing. I can't tell.

On repeat runs, that "is being updated..." is not there anymore; if that's useful.

-----------------------------------------------------------------------------
... some stuff printed with any wine run ....
011c:err:setupapi:create_dest_file failed to create L"C:\\windows\\system32\\atl100.dll" (error=80)
0130:err:setupapi:create_dest_file failed to create L"C:\\windows\\system32\\atl100.dll" (error=80)
0130:err:winediag:gnutls_process_attach failed to load libgnutls, no support for encryption
0130:err:winediag:process_attach failed to load libgnutls, no support for pfx import/export
wine: configuration in L"/home/deck/.steam/steam/steamapps/compatdata/221680/pfx" has been updated.
regsvr32: Successfully registered DLL '/usr/lib32/wine/i386-unix/wineasio32.dll.so'
'/usr/lib/wine/x86_64-windows/wineasio64.dll' -> '/home/deck/.steam/steam//steamapps/compatdata/221680/pfx/drive_c/windows/system32/wineasio64.dll'
regsvr32: Successfully registered DLL '/usr/lib/wine/x86_64-unix/wineasio64.dll.so'
=============================================================================

At this point, we can use an ASIO tester app, `VBAsioTest_1014`
Download it, and run the EXE with the Rocksmith's Wine so it uses all the installed things.

-----------------------------------------------------------------------------
WINEPREFIX=$STEAMLIBRARY/steamapps/compatdata/221680/pfx "$PROTON/bin/wine" ./VBASIOTest32.exe
=============================================================================

ANOTHER ISSUE (now a fatal one I assume)

Open it up, select "WineASIO" in the window-top-menu in `Devices` dropdown.
The log claims "Driver not found" despite seeing WineASIO ...!!

What am I missing?!

-----------------------------------------------------------------------------
#0001 ------------------------------------------------------
#0002 (32Bits) TEST ASIO DEVICE: WineASIO
#0003 OPEN ASIO DEVICE Error: Driver not found
=============================================================================

Now the last thing, modify Rocksmith to run itself correctly.

Copy the WineASIO files to the Rocksmith game folder.
Do all those edits to all .ini files as the guide says.

Add some env vars to the Rocksmith Steam-command
(Steam games library -> RS2014 -> Properties... -> Launch Options)

-----------------------------------------------------------------------------
LD_PRELOAD=/usr/lib32/libjack.so PIPEWIRE_LATENCY=256/48000 %command%
=============================================================================

And it doesn't work. I still get the usual message. No crash, but no audio output.
Still complains about not finding an output device.

I've disabled all devices but Lexicon Alpha in `pavucontrol` Configuration tab.

I also have qpwgraph open, monitoring that graph.
No Rocksmith entry, no change after running Rocksmith.

=============================================================================
```

**Comment by MilanKladivko** [comment] 2024-07-05 12:39
The RS_ASIO-log.txt file looks suspicious, though I have no idea what it all means.

[RS_ASIO-log.txt](https://github.com/user-attachments/files/16109790/RS_ASIO-log.txt)

**Comment by theNizo** [comment] 2024-07-06 12:19
I made the issue template so that I don't get issues like this that basically tell me "figure everything out yourself".

I will only continue helping you when you fill out the complete template.

* **What appears to be the problem? (Describe it as best as you can)** - Not filled out
* **Did you notice any other unexpected behavior?** - Yes, clearly, but you could have placed it somewhere more convenient for me to find. Not in a giant log, but maybe somewhere before this wall of text.
* **What did you try already?** - No notes on that whatsoever.
* **Did you do any of the steps differently or leave them out?** - Technically, you did, but I'm not gonna look for differences in that huge log of yours.

Lucky for you, I only noticed that when I was midway through your "log".

> The `./wineasio-register` command prints some errors

Some time ago, the guides said that these were normal. I will add that note to the guides again.

> OPEN ASIO DEVICE Error: Driver not found

That is your issue.

I currently can't test the default behavior, since VBASIO doesn't even show up on my system when I run it with Proton's wine binaries.

You can try one thing.

1. patch ~/.wine
1. launch VBASIO test with normal wine.

Let's see if that works.

**Comment by theNizo** [comment] 2024-07-25 09:51
Closing because of no further interaction.

**Closed by theNizo** 2024-07-25 09:51 UTC
Labels: help wanted, invalid

**Comment by joaociocca** [comment] 2024-08-21 02:55
after dealing with [that other problem](https://github.com/theNizo/linux_rocksmith/discussions/55), I found myself having this one. But solved it when I found out [this other answer](https://github.com/mdias/rs_asio/issues/430#issuecomment-2066245295) and changed `EnableWasapiOutputs=1`  - running on a Dell G5 laptop with Garuda installed, just for the record in case someone (like future me) gets this problem too =p
